name: Hello GitHub Actions  # 工作流名称

on:                          # 触发条件
  push:
    branches: [ main ]       # 当 push 到 main 分支时触发
  pull_request:
    branches: [ main ]       # 当 PR 目标为 main 时触发

jobs:
  say-hello:                 # Job 的 ID
    runs-on: macos-latest

    steps:
      - name: 签出代码        # 步骤 1：签出仓库代码
        uses: actions/checkout@v4

      - name: 打个招呼        # 步骤 2：运行命令
        run: echo "Hello, GitHub Actions! 🎉"

      - name: 安装 cmake
        run: brew install cmake

      - name: 进行编译
        run: mkdir -p build && cd build && cmake .. && make

      - name: 运行程序
        run: ./build/actions_test